name: example
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animated_qr_scanner:
    path: ../
  google_mlkit_commons: ^0.7.1
  google_mlkit_barcode_scanning: ^0.12.0
  camera: ^0.11.0+2
  image: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#  assets:
#    - assets/