name: flutter_animated_barcode_scanner
description: This package simplifies adding barcode scanning to your app with an animated finder that guides users and highlights barcodes. It's a powerful tool to enhance your app!
version: 1.0.0
homepage: https://romanticdeveloper.com
repository: https://github.com/minhhung2556/romantic_project_flutter_animated_barcode_scanner

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: any
  google_mlkit_barcode_scanning: any
  camera: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: